# -*- coding: utf-8 -*-
"""
Map data loader and registry for Ming Dynasty RPG.
Loads static maps (north, south) and dynamically loads historical scene JSON files.
GENERATED BY MAP EDITOR.
"""

import json
from pathlib import Path

MAP_WIDTH = 40
MAP_HEIGHT = 30

BASE_DIR = Path(__file__).resolve().parent
SCENES_DIR = BASE_DIR / "assets" / "scenes"

# ==========================================
# 1. 钟离县-北 (Zhongli County - North)
# ==========================================

GROUND_MAP_NORTH = [
    "gggggggggggggggggggggggggggggggggggggggg",
    "gggggggggggggggggggggggggggggggggggggggg",
    "gggggggggggggggggggggggggggggggggggggggg",
    "ggggggggggggggrrrcgggggggggggggggggggggg",
    "ggggggggggggggvggvgggggggggggggggggggggg",
    "wwwwwowwwwwgggvggvgggggggggggggggggggggg",
    "wwwwwowwwwwgggvggvgggggggggggggggggggggg",
    "wwwwwowwwwwgggvggrrrrrrrrrrrrrrrcggggggg",
    "wwwwwowwwwwgggvgggggggggggggggggvggggggg",
    "wwwwwowwwwwgggvgggggggggggggggggvggggggg",
    "wwwwwowwwwwgggvgggggggggggggggggvggggggg",
    "wwwwwowwwwwgggxrrrrrrrrrcgggggggvggggggg",
    "wwwwwowwwwwgggvgggggggggvgggggggvggggggg",
    "wwwwwowwwwwgggvgggggggggvgggggggvggggggg",
    "wwwwwowwwwwgggvgggggggggvgggggggvggggggg",
    "rrrrrbrrrrrgggvgggggggggxrrcggggvggggggg",
    "wwwwwowwwwwgggvgggggggggvggvggggvggggggg",
    "wwwwwowwwwwgggvgggggggggvggvggggvggggggg",
    "wwwwwowwwwwgggvgggggggggvggvggggvggggggg",
    "wwwwwowwwwwgggxrrrrrrcggvggvggggvggggggg",
    "wwwwwowwwwwgggvggggggvggvggvggggvggggggg",
    "wwwwwowwwwwgggvggggggvggvggvggggvggggggg",
    "wwwwwowwwwwgggvggggggvggvggvggggvggggggg",
    "wwwwwowwwwwgggvggggggxrrcggvggggvggggggg",
    "wwwwwowwwwwgggvggggggvgggggvggggvggggggg",
    "wwwwwowwwwwgggvggggggvgggggvggggvggggggg",
    "wwwwwowwwwwgggvggggggvgggggvggggvggggggg",
    "wwwwwowwwwwgggrrrrrrrxrrrrrcggggvggggggg",
    "wwwwwowwwwwgggvgggggggggggggggggvggggggg",
    "wwwwwowwwwwgggvgggggggggggggggggvggggggg",
]

OBSTACLE_MAP_NORTH = [
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    "T......................................T",
    "T....PPPPPPPPPPP..........MMMMMMMMMM...T",
    "T....P.........P..........M........M...T",
    "T....P.RRR.....P..........M.RRRR...M...T",
    ".....P.WWDW....P..........M.RRRR...M....",
    ".....P.........P..........M.WWDW...M....",
    ".....P...J.....P..........M........M....",
    ".....P.........P..........MMMM.MMMMM....",
    ".....PPPPPPPPP.P...............F........",
    "T..............................F.......T",
    "T......................RRR.....F.......T",
    "T......B...............WWDW....F.......T",
    "T.....U.X......................F.......T",
    "T..............................F.......T",
    ".......S.......................F........",
    "...............................F........",
    "T...................F.FFFFF.FFFF.......T",
    "T...................F..................T",
    "T...................F..mmmmmmmmmiii....T",
    "T...................F..mmmmmmmmmiii....T",
    "T...................F..mmmmmmmmmiii....T",
    "T...................F..mmmmmmmmmiii....T",
    "T...................F..vvvvvvvvviii....T",
    "T...................F..vvvvvvvvviii....T",
    "T...................F..vvvvvvvvviii....T",
    "T...................F..................T",
    "T...................FFFFFFFFFFFF........",
    "T......................................T",
    "TTTTTTTTTTTT.....TTTTTTTTTTTTTT...TTTTTT",
]

NPCS_NORTH = [
    {
        "id": "elder",
        "name": "村长朱五四",
        "sprite": "elder",
        "x": 24,
        "y": 13,
        "dialogue": [
            "重八啊（朱元璋小名），咱家已经三天没米下锅了……",
            "这世道，元朝暴政，贪官污吏横行，百姓民不聊生啊！",
            "听说皇觉寺的师父在招收行童，好歹能混口饭吃，你快去看看吧。"
        ]
    },
    {
        "id": "friend",
        "name": "徐达",
        "sprite": "friend",
        "x": 16,
        "y": 13,
        "dialogue": [
            "重八哥！你可算来了！",
            "听说你拿了个破碗，是要准备去化缘打天下吗？",
            "不管你走到哪，我徐达都一辈子跟着你干！",
            "等我们长大了，一定要推翻这不给穷人活路的元朝！"
        ]
    },
    {
        "id": "monk",
        "name": "皇觉寺老和尚",
        "sprite": "monk",
        "x": 28,
        "y": 7,
        "dialogue": [
            "阿弥陀佛，施主骨相奇特，日后必成大器。",
            "如今乱世，佛门也难避兵燹之灾。这口【行军破碗】便赠予施主。",
            "持此碗者，可纳百川之志，聚天下之贤。去吧，去拯救这苍生百姓！"
        ]
    },
    {
        "id": "wolf_1",
        "name": "野狼",
        "sprite": "wolf",
        "x": 10,
        "y": 8,
        "dialogue": ["嗷呜——！一只饥饿的野狼正虎视眈眈地盯着你！"]
    },
    {
        "id": "tiger_1",
        "name": "猛虎",
        "sprite": "tiger",
        "x": 30,
        "y": 15,
        "dialogue": ["吼——！百兽之王猛虎发出了震耳欲聋的咆哮！"]
    }
]

CHESTS_NORTH = [
    {
        "x": 12,
        "y": 13,
        "opened": False,
        "item": "破旧的木棍",
        "dialogue": "你打开了废墟中的宝箱，获得了【破旧的木棍】！这可以当作防身的武器。"
    }
]

CONNECTIONS_NORTH = {
    "south": {
        "map_id": "south",
        "start_x": 14,
        "start_y": 0
    },
    "east": {
        "map_id": "huangjuesi",
        "start_x": 1,
        "start_y": 15
    }
}

# ==========================================
# 2. 钟离县-南 (Zhongli County - South)
# ==========================================

GROUND_MAP_SOUTH = [
    "wwwwwowwwwwgggvgggggggggggggggggvggggggg",
    "wwwwwowwwwwgggvgggggggggggggggggvggggggg",
    "wwwwwowwwwwgggvgggggggggggggggggvggggggg",
    "wwwwwowwwwwgggvgggggggggggggggggvggggggg",
    "wwwwwowwwwwgggrrrrrrrrrrrrrrrrrrcggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "rrrrrbrrrrrgggxrrrrrrrrrrrrrrrrrrrrrrrrr",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggvggggggggggggggggggggggggg",
    "wwwwwowwwwwgggrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "wwwwwowwwwwggggggggggggggggggggggggggggg",
    "wwwwwowwwwwggggggggggggggggggggggggggggg",
]

OBSTACLE_MAP_SOUTH = [
    "TTTTTTTTTTTT.....TTTTTTTTTTTTTT...TTTTTT",
    "T......................................T",
    "T....PPPPPPPPP.P..........MMMMMMMMMM...T",
    "T....P.........P..........M........M...T",
    "T....P.........P..........M........M...T",
    ".....P.........P..........M........M....",
    ".....P.........P..........M.RRR....M....",
    ".....P.........P..........M.WWDW...M....",
    ".....P.........P..........M........M....",
    ".....PPPPPPPPP.P..........MMMMMMMMMM....",
    "T......................................T",
    "T......................................T",
    "T......B...............................T",
    "T.....U.X..............................T",
    "T......................................T",
    ".......S................................",
    "........................................",
    "T...................FFFFFFFFFFFF.......T",
    "T...................F..........F.......T",
    "T...................F..iiiiii..F.......T",
    "T...................F..iiiiii..F.......T",
    "T...................F..iiiiii..F.......T",
    "T...................F..iiiiii..F.......T",
    "T...................F..vvvvvv..F.......T",
    "T...................F..vvvvvv..F.......T",
    "T...................F..vvvvvv..F.......T",
    "T...................F..........F.......T",
    "T...................FFFFF.FFFFFF.......T",
    "T......................................T",
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
]

NPCS_SOUTH = [
    {
        "id": "lion_1",
        "name": "狂狮",
        "sprite": "lion",
        "x": 15,
        "y": 10,
        "dialogue": ["吼——！一头金毛狂狮正张开血盆大口！"]
    },
    {
        "id": "chang",
        "name": "常遇春",
        "sprite": "chang",
        "x": 10,
        "y": 12,
        "dialogue": [
            "俺乃常遇春是也！手持长枪，万军之中取敌将首级如探囊取物！",
            "重八哥，俺看你气宇轩昂，绝非等闲之辈。",
            "等天下大乱，俺愿做你的开路先锋，随你南征北战，建立不世之功！"
        ]
    },
    {
        "id": "merchant",
        "name": "行脚商人",
        "sprite": "merchant",
        "x": 16,
        "y": 15,
        "dialogue": [
            "走南闯北，倒卖些南北杂货。如今世道太乱，生意不好做啊！",
            "小师父，看你拿着个破碗，是要去化缘吗？",
            "听闻南边的山林里有土匪出没，你可千万要小心啊！"
        ]
    },
    {
        "id": "farmer",
        "name": "农夫阿福",
        "sprite": "farmer",
        "x": 24,
        "y": 20,
        "dialogue": [
            "唉，今年的收成大半都要交纳给官府做军饷，我们自己连稀粥都喝不上了。",
            "这日子，真是没法过了！什么时候才能有个明君来救救我们啊……"
        ]
    }
]

CHESTS_SOUTH = [
    {
        "x": 28,
        "y": 3,
        "opened": False,
        "item": "精致的草鞋",
        "dialogue": "你打开了树林中的宝箱，获得了【精致的草鞋】！穿上它感觉脚步轻盈了许多。"
    }
]

CONNECTIONS_SOUTH = {
    "north": {
        "map_id": "north",
        "start_x": 14,
        "start_y": 28
    }
}

# ==========================================
# 3. 场景注册表 (Scene Registry)
# ==========================================

MAPS = {
    "north": {
        "name": "濠州府 · 钟离县-北",
        "ground": GROUND_MAP_NORTH,
        "obstacle": OBSTACLE_MAP_NORTH,
        "npcs": NPCS_NORTH,
        "chests": CHESTS_NORTH,
        "connections": CONNECTIONS_NORTH,
        "min_level": 1
    },
    "south": {
        "name": "濠州府 · 钟离县-南",
        "ground": GROUND_MAP_SOUTH,
        "obstacle": OBSTACLE_MAP_SOUTH,
        "npcs": NPCS_SOUTH,
        "chests": CHESTS_SOUTH,
        "connections": CONNECTIONS_SOUTH,
        "min_level": 2
    }
}

def load_dynamic_scenes() -> None:
    if SCENES_DIR.exists():
        for path in SCENES_DIR.glob("*.json"):
            try:
                with open(path, "r", encoding="utf-8") as f:
                    scene_data = json.load(f)
                    scene_id = path.stem
                    MAPS[scene_id] = scene_data
                    print(f"Loaded dynamic scene: {scene_id} ({scene_data['name']})")
            except Exception as e:
                print(f"Error loading scene {path}: {e}")

load_dynamic_scenes()